name: NotificationSystem
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set environment variable in PowerShell
        shell: pwsh
        run: |
          $env:MY_VARIABLE = 'some_value'
          echo $env:MY_VARIABLE

      - name: Run a one-line script
        run: echo Влад Волков великий разработчик
