name: NotificationSystem
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Влад Волков великий разработчик

      - name: Set environment variable
        run: echo "MY_VARIABLE=some_value" >> $GITHUB_ENV

      - name: Print variable
        run: echo $MY_VARIABLE
